import UserModel from "../models/userModel.js";
import bcrypt from "bcryptjs";
import { generateToken } from "../config/utils.js";
import cloudinary from "../config/cloudinary.js";
import sanitizeHtml from "sanitize-html";

//Signup
export const signup = async(req, res) =>{
    const {fullName, email, password, bio} = req.body
    try {

        if (!fullName || !password || !email) {
            return res.status(400).json({message: "All fields are required"})
        }
        if (password.length < 8){
            return res.status(400).json({message: "Password must be at least 8 characters"})
        }

        const user = await UserModel.findOne({email});

        if (user) return res.status(400).json({message: "email already exists"});

        //salt is for password security and salt is generated by random alg and it generates diff hash eventhough the pwd is same
        //Default salt value is 10. The more the number the more secure the pwd, but slower the hashing

        const salt = await bcrypt.genSalt(10);
        //password + salt = hashedPassword
        const hashedPassword = await bcrypt.hash(password, salt);
        
        const sanitizedBio = sanitizeHtml(bio || "", {
            allowedTags: ['b', 'i', 'em', 'strong', 'u'],
            allowedAttributes: {}
        });

        //storing user details in newUser and we have created userData from the user response and Storing the userData in mongoDb
        const newUser = new UserModel({
            fullName,
            email,
            password: hashedPassword,
            bio : sanitizedBio
        })

        if (newUser){
            // generate jwt token here
            generateToken(newUser._id, res)
            await newUser.save()
            res.status(201).json({
                _id: newUser._id,
                fullName: newUser.fullName,
                email: newUser.email,
                profilePic: newUser.profilePic,
                bio: newUser.bio
            })
        }
        else{
            res.status(400).json({message: "Invalid user data"})
        }

    } catch (error) {
        console.log("Error in signup controller", error.message)
        res.status(500).json({message: "Internal Server Error"})
    }
}




//login
export const login = async(req, res) => {
    // retriving email and pwd from body
    const {email, password} = req.body;
    try {
        const user = await UserModel.findOne({email})
    if (!user){
        return res.status(400).json({message: "Invalid credentials"})
    }
    // if user email is exist will check the password using compare method
    const isMatch = await bcrypt.compare(password, user.password)
    if (isMatch) {
        generateToken(user._id, res)
        res.status(200).json({
            _id: user._id,
            fullName: user.fullName,
            email: user.email,
            profilePic: user.profilePic

        })
    } else {
        return res.status(400).json({message: "Invalid credentials"})
    }

    } catch (error) {
        console.log("Error in login controller", error.message);
        res.status(500).json({message: "Internal Server Error"})
    }
}




// logout
export const logout = async (req, res) => {
  try {
    res.clearCookie("token", {
      httpOnly: true,
      sameSite: "strict",
      secure: process.env.NODE_ENV !== "development"
    });
    res.status(200).json({ success: true, message: "Logged out successfully" });
  } catch (error) {
    console.log("Error in logout controller", error.message);
    res.status(500).json({ message: "Internal Server Error" });
  }
};




//update Profile
export const updateProfile = async(req, res) =>{
    try {
        const {profilePic, bio, fullName} = req.body;
        // To check which user is
        const userId = req.user._id;

        const updates = {}

        // sanitize and validate bio
        if (bio) {
            const sanitizeBio = sanitizeHtml(bio, {
                allowedTags: ['b', 'i', 'em', 'strong', 'u'],
                allowedAttributes: {}
            });

            if (sanitizeBio.length >150) {
                return res.status(400).json({ message: "Bio must be under 150 characters" });
            }
            updates.bio = sanitizeBio;
        }

        // upload and profile pic 

        if(profilePic){
            // get user to retrieve old profile pic
            const user = await UserModel.findById(userId)

            // delete old image if exists
            if (user.profilePicId){
                await cloudinary.uploader.destroy(user.profilePicId)
            }

            // Upload new image
            const uploadResponse = await cloudinary.uploader.upload(profilePic);
            updates.profilePic = uploadResponse.secure_url;
            updates.profilePicId = uploadResponse.public_id;
        }

        if (fullName) {
            updates.fullName = fullName.trim();
        }

        if (Object.keys(updates).length === 0) {
            return res.status(400).json({ message: "Nothing to update" });
        }

        
        // update user
        const updateUser = await UserModel.findByIdAndUpdate(
            userId,
            updates,
            {new: true}
        );

        res.status(200).json({success: true, user: updateUser});

     } catch (error) {
        console.log("Error in updateProfile:", error);
        res.status(500).json({ message: "Internal Server Error" });
    }
};

// check authorized user
export const checkauth = (req, res) =>{
    try {
        res.status(200).json({success: true, user: req.user});
    } catch (error) {
        console.log("Error in checkauth controller", error.message);
        res.status(500).json({message: "Internal Server Error"});
    }
}
